--- 
- name: '[EL] create users on the server'
  user:
    name: "{{ item.name }}"
    shell: '/bin/bash'
    uid: "{{ item.GUID | default( omit, true) }}"
    state: present
    groups: adm,wheel,systemd-journal
  with_items: "{{ ssh_user }}"
  when: ansible_os_family == "RedHat" 

- name: '[Ubuntu] Create users on the server'
  user:
    name: "{{ item.name }}"
    shell: '/bin/bash'
    uid: '{{ item.GUID | default( omit, true ) }}'
    state: present
  with_items: "{{ ssh_user }}"
  when: ansible_os_family == "Debian"

- name: Set authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: present   
    key: '{{ item.ssh_key }}'
  with_items: "{{ ssh_user }}"
  when: 
    -  item.ssh_key is defined 
    -  item.ssh_key != '' 
